# Generated by Django 4.0.6 on 2022-07-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('sub_content', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to='news/')),
                ('image_caption', models.CharField(max_length=128, null=True)),
                ('published_datetime', models.DateTimeField(null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('is_editor_choice', models.BooleanField(default=False)),
                ('is_trend', models.BooleanField(default=False)),
                ('is_interview', models.BooleanField(default=False)),
                ('is_investigation', models.BooleanField(default=False)),
                ('is_article', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('is_videonews', models.BooleanField(default=False)),
                ('is_photonews', models.BooleanField(default=False)),
                ('is_adviced', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.region')),
                ('tags', models.ManyToManyField(related_name='news', to='news.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
